version: 2.1
jobs:
  build-deploy:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/todo-seorangeksa
    steps:
      - run: sudo apt update && sudo apt install git rsync -y && git --version

      - add_ssh_keys:
          fingerprints: 
            - 'cf:bc:41:e6:6c:f6:4d:21:1e:8a:48:33:4e:60:29:b6'

      - checkout
      - run: npm cache clean --force && sudo rm -rf node_modules package-lock.json && yarn --version
      - run: yarn install
      - run: yarn build
      - run: ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
      - run: rsync -avce ssh --delete ~/todo-seorangeksa/public/ ${SSH_ROOT}@${SSH_HOST}:/var/www/todo.seorangeksa.com

workflows:
  build:
    jobs:
      - build-deploy